workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-latest

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - run: $(npm bin)/lerna bootstrap
      - run: $(npm bin)/lerna run prepare # work around for https://github.com/npm/npm/issues/19479
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)
  node-v10:
    <<: *base
    docker:
      - image: node:10
  node-latest:
    <<: *base
    docker:
      - image: node:latest
