workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-lts
      - node-v10
      - node-v12

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:lts-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: node cli.js https://jsconf.jp/2019 --browsers chromium,firefox,webkit --locales en-US,ja-JP
  node-lts:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)
      - run: npm run prepare && node cli.js https://jsconf.jp/2019 --browsers chromium,firefox,webkit --locales en-US,ja-JP
      - store_artifacts:
          path: __screenshots__
  node-v10:
    <<: *base
    docker:
      - image: circleci/node:10-stretch-browsers
  node-v12:
    <<: *base
    docker:
      - image: circleci/node:12-stretch-browsers
