workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-lts
      - node-v10
      - node-v12
      - node-v14

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:lts-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: node cli.js http://example.com --locales en-US,ja-JP --viewports 1680x1050,828x1792
      - run: node cli.js http://leko.jp --depth 0
      - run: node cli.js https://darkmodejs.learn.uno --depth 0 --prefers-color-schemes=light,dark
  node-lts:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run prepare
      - run: node cli.js http://example.com --locales en-US,ja-JP --viewports 1680x1050,828x1792
      - run: node cli.js http://leko.jp --depth 0
      - run: node cli.js https://darkmodejs.learn.uno --depth 0 --prefers-color-schemes=light,dark
      - run: bash <(curl -s https://codecov.io/bash)
  node-v10:
    <<: *base
    docker:
      - image: circleci/node:10-stretch-browsers
  node-v12:
    <<: *base
    docker:
      - image: circleci/node:12-stretch-browsers
  node-v14:
    <<: *base
    docker:
      - image: circleci/node:14-stretch-browsers
